### ISSUE TITLE
dbloader errors 

### ISSUE THREAD

**Issue by Mullick** [cryptocoinexplorer/Open-Source-CCE-4.0#1]
Im having some trouble loading a chain with the dbloader. 

Every 10k or so block its stops with the following error 

Processing Block:  61872  of  203222 ^M\Main Loop cannot concatenate 'str' and 'int' objects

A restart resumes the loader but im wondering if you have any ideas as to where it could be getting hung up. The chain is Legendarycoin if that is of any help

Thanks!

**Comment by cryptocoinexplorer** [comment]
The main loop timer (cowtime) is timing out. The standard timeout is 5 minutes.
When the dbloader is run with the new database option (-n) this timeout is extended to 24 hours.
If the initial database load is interrupted after block 101, continue the database load using the (-l) option. This also extends the timeout to 24 hours but does not run the database initialization functions.

The error it self is a bug. It is essentially an error of an error. Cowtime is throwing an exception that python is seeing as an int when it goes to log the error. I will correct it in the next commit.

**Comment by Mullick** [comment]
Awesome thank you. I saw that noted in the docs but the error threw me off a bit. Thanks for the quick response.
